{%- if cookiecutter.wsgi_server == "uwsgi" -%}
{% set web_command = "uwsgi --http 0.0.0.0:5000 --module " + cookiecutter.app_name + ".wsgi:app" %}
{%- elif cookiecutter.wsgi_server == "gunicorn" -%}
{% set web_command = "gunicorn -b 0.0.0.0:5000 " + cookiecutter.app_name + ".wsgi:app" %}
{%- else -%}
{% set web_command = "flask run -h 0.0.0.0" %}
{%- endif -%}
# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: {{cookiecutter.app_name}}
    build: .
    command: {{web_command}}
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/{{cookiecutter.app_name}}.db
    volumes:
      - ./{{cookiecutter.app_name}}:/code/{{cookiecutter.app_name}}
      - ./db/:/db/
    ports:
      - "5000:5000"
